---
title: "Unit 6: Polymorphism and Symbolic Computing"
format:
  html:
    toc: true
    code-fold: false
    highlight-style: tango
  pdf:
    documentclass: article
    geometry:
      - margin=1in
    toc: true
    number-sections: true
---

# Running the codebase 
Let's prepare by running the codebase for the computer algebra project:
```{julia}
#| echo: true
using Pkg;
cd("../../MATH2504_2026_ProjectB");
Pkg.activate(".");
Pkg.instantiate(); 
include("../../MATH2504_2026_ProjectB/poly_factorization_project.jl"); # load/run the functions and types of the project codebase
```

Now we have access to basic polynomials and algebraic operations acting on polynomials:
```{julia}
x = x_poly(PolynomialDense);
z = zero(PolynomialDense);
p=(3x^2-x)*x
```

# Symbolic Computation

To compute *exactly* means no error is introduced during arithmetic --- something *not* true when working with floats.  In a computer algebra system $\sqrt{2} = \sqrt{2}$ and not $\sqrt{2} = 1.41\ldots$ as one may expect.

Our interest is performing *exact* arithmetic in rings with efficient algorithms.  In particular we are interested in the *ring of integers*
$$
\mathbb{Z} = \{0, -1, 1, 2, -2, 3, -3, \ldots \}
$$
and *polynomials* 
$$
\mathcal{R}[x] = \left\{ \sum_{k=0}^{N} a_kx^k \, s.t. \, k \in \mathbb{N},\, a_k \in \mathcal{R} \right\}.
$$

## Elementary Algebra

It is first necessary to establish terms and definitions.

Let $\mathbb{N} = \{0,1,2,\ldots\}$ be the set of *natural numbers*, $\mathbb{Z} = \{\ldots,-2,-1,0,1,2,\ldots\}$ be the *integers* and $\mathbb{P}$ be the set of odd primes.

### Definition (Ring) 

A ring $\mathcal{R}$ is a set with addtion $(+)$ and multiplciation $(\cdot)$ satisfying the following conditions called the *ring axioms*:

- $(\mathcal{R},+)$ is an abelian group, that is:
    - $(+)$ is associative *and* commutative,
    - $\exists b \in \mathcal{R}$ called the *additive identity* satisfying $\forall a \in \mathcal{R} \; a + b = a$,
    - $\forall a \in \mathcal{R}\; \exists b \in \mathcal{R}$ called the *additive inverse* satisfying $a + b = 0$.
-  $(\mathcal{R},\cdot)$ is a monoid, that is:
    -  $(\cdot)$ is associative, and
    -  $\exists b \in \mathcal{R}$ called the *multiplicative identity* satisfying $\forall a \in \mathcal{R}; \; a \cdot b = b \cdot a = a$
-  Multiplication *distributes* over addition.  That is, $\forall a,b,c \in \mathcal{R}$:
    - $a \cdot (b+c) = (a \cdot b) + (a \cdot c)$
    - $(b+c) \cdot a = (b \cdot a) + (c \cdot a)$
    
#### Examples {-}
1.  The $\mathcal{R} = \{ 0 \}$ (the *zero ring*) is a trivial ring.
1.  The naturals $\mathbb{N}$ do *not* form a ring as they lack additive idenity.
1.  Arithmetic on the clock forms a ring.

### Definition (Zero Divisor) 
An element $a \in \mathcal{R}$ is called a *zero divisor* if there is nonzero $b \in \mathcal{R}$ such that $ab = 0$.

### Definition (Integral Domain)
An integral domain is a nonzero commutative ring without zero divisors.

#### Examples {-}
1.  The integers $\mathbb{Z}$ form an integral domain.
1.  'Clock arithmetic' does not form an integral domain because, for instance, $3 \cdot 4$ is 12 which is the zero.

### Definition (Field) 
A ring $\mathcal{R}$ is also a *field* when each non-zero element has a *multiplicative inverse*.  Equivalently, $\mathcal{R}$ is a ring when
$$
\forall a \in \mathcal{R}^{\neq 0};\; \exists b \in \mathcal{R} \; : \; a \cdot b.
$$

#### Examples {-}
For instance, the *rationals* $$\mathbb{Q} = \left\{ \frac{a}{b} \,:\, a,b \in \mathbb{Z}, \, b \neq 0 \right\}$$
is a field because $\frac a b \cdot \frac b a = 1$ when $a,b \neq 0$.

### Theorem (Division Algorithm) 
Let $a,b \in \mathbb{Z}$ with $b > 0$.  There is *unique* $q$ and $r$ (called the *quotient* and *remainder*) satisfying
$$a = b \cdot q + r$$
with $r < |q|$.

```{julia}
# An example
a, b = 23, 7
```

```{julia}
q = a ÷ b # \div + [TAB]
```

```{julia}
r = a % b
```

```{julia}
a == b * q + r
```

```{julia}
# Recall: abstract type «name» <: «supertype» end
function remainder(a::T, b::T) where T <: Integer 
    #Note that later we'll extend this to integral domains
    
    #short circuit evalution gives cheeky if statements
    a < 0 && return remainder(-a, b) #later replace `0` with `zero(T)`
    a < b && return a
    return remainder(a-b, b)
end
```

```{julia}
#note there is an in-built `rem`
remainder(23, 7), rem(23, 7), 23 % 7, 23 - (23 ÷ 7)*7
```

```{julia}
remainder(15, 5), remainder(4, 101), remainder(125, 4)
```

```{julia}
function quo(a::T, b::T) where T <: Integer
    a < 0 && return -quo(-a,b)
    a < b && return 0
    return 1 + quo(a-b, b)
end
```

```{julia}
quo(15, 5), quo(4, 101), quo(125, 4)
```

```{julia}
for (a,b) in [(15, 5), (4, 101), (125,4 )]
    q, r = quo(a, b), rem(a, b)
    println("$a = $q⋅$b + $r")
end
```

Of course, in Julia we have `%` and `÷` for remainder and  and quotient.

(Note that in Python `//` is the quotient whereas in Julia `//` defines a rational type).

```{julia}
23 // 7, float(23//7)  #The first // is a rational type #!!! Note in Python // is ÷
```

Incidentally, another way to express the quotient/remainder relation is by way of "proper" fractions.
$$
23 = 3\cdot 7 + 2 \iff \frac {23} 7 = 3 + \frac {2} {7}
$$

```{julia}
(23 ÷ 7), (23 % 7) // 7
```

```{julia}
23 // 7 == (23 ÷ 7) + (23 % 7) // 7
```

***

## Elementary Number Theory
### Residue Classes
The sets $\mathbb{Z}_n = \{0,1,\ldots,n-1\}$ for $n \in \mathbb{N}$ are rings called *residue classes* when addition and multiplication are done 'mod n'.  This is sometimes called 'clock arithmetic' as three hours past eleven is two because $11 + 3 \cong 2 \mod 12$. 

We say/write 
$$
a \cong b \mod c
$$ 
when *$a$ is congruent to $b$ modulo $c$*.  Also:
$$
a \cong b \mod c \iff \mathop{\textrm{rem}}(a,c) = b \iff \text{a \% c = b}
$$

We have already seen something similar with overflow. In particular, working in an 8-bit register is essentially doing arithmetic modulo $2^8$.

```{julia}
UInt8(2^8-3) + UInt8(4)
```

```{julia}
(2^8-3 + 4) % 2^8
```

### Symmetric Mod

We may also use negatives values, here 
$\mathbb{Z}_n = \{ -{\rm quo}(n,2),\, 0,\,\ldots,\,{\rm quo}(n,2)\}$. For instance, $\mathbb{Z}_7 = \{-3,-2,-1,0,1,2,3\}$ and
$$
5 \cong -2 ~{\rm smod}~ 7.
$$
We do not use this notation and simply move use `mod` as `smod` when we want as there is no effect on the theory and presentation.

***

#### Example (Addition Table) {-}
$\mathbb{Z}_6 = \{0,\ldots,5\}$ has the following *addition table*

```{julia}
n = 6
Z_n = 0:(n-1)
typeof(Z_n)
A = [(x+y) % n for y in Z_n, x in Z_n]
```

Notice: 
 1.  the addition table is symmetric (equal to its transpose) which can only happen when the addition is commutative,
 1.  the additive identity is $0$,
 1.  each column (and row) has $0$ and thereby each element has an additive inverse: for instance, the third column indicates that $2$ has additive inverse $4$ and correspondingly $2 + 4 \cong 0 \mod 6$.

```{julia}
(A .== 0)
```

```{julia}
additive_inverses = [findfirst((A .== 0)[:,k+1])-1 for k in Z_n]
println(additive_inverses)  # print horizontally instead of vertically
```

#### Example (Multiplication Table) {-}

$\mathbb{Z}_6$ has the following *multiplication table*

```{julia}
M = [(x*y) % n for y in Z_n, x in Z_n]
```

Notice:
1.  the multiplicative identity is $1$,
1.  *not* all rows contain one, which means there are some elements that do *not* have *multiplicative inverse*.  For instance there is no $b \in \mathbb{Z}_6$ such that $2 \cdot b \cong 1 \mod 6$.

```{julia}
println([(2*y) % n for y in Z_n])
```

```{julia}
mult_inverses = Z_n[[sum((M .== 1)[:,k+1]) > 0 for k in Z_n]]
println("Elements with a multiplicative inverse: ", mult_inverses )
println("Elements withoout a multiplicative inverse: ", setdiff(Z_n,mult_inverses))
```

***

Notice $\mathbb{Z}_6$ is *not* a field because, recall, there is no multiplicative inverse for $2$.  However, $\mathbb{Z}_p$ is a field when $p$ is a prime number.

#### Example {-}

$\mathbb{Z}_5 = \{0,\ldots,4\}$ is a field and has the following multiplication table. 

```{julia}
n = 5
Z_n = 0:(n-1)
M = [(x*y) % n for y in Z_n, x in Z_n]
```

```{julia}
mult_inverses = Z_n[[sum((M .== 1)[:,k+1]) > 0 for k in Z_n]]
println("Elements with a multiplicative inverse: ", mult_inverses )
println("Elements withoout a multiplicative inverse: ", setdiff(Z_n,mult_inverses))
```

Notice every column (and row) contains $1$ asides the first column (and row) which corresponds to $0$.  For instance, the third column indicates the inverse of $3$ is $2$ and correspondingly $3 \cdot 2 \cong 1 \mod 5$.

***

### Greatest Common Divisor

The *greatest common divisor* is one of the fundamental operations of a computer algebra system.  For instance, we need `gcd` to reduce fractions to their canonical form.

#### Def (GCD)

Let $a,b \in \mathbb{Z}$ not both 0.  We say $g \in \mathbb{Z}$ is the *greatest common divsor* of $a$ and $b$, denoted $\gcd(a,b)$, when
1.  $g | a$ and $g | b$ ($g$ is a common divisor), 
1.  $h | a \;\wedge\; h | b \implies h | g$ (greatest),
1.  $g > 0$ (required for uniqueness) 

##### Example (GCD) {-}
- The $\gcd(6,4) = \gcd(2\cdot 3, 2 \cdot 2) = 2$.
- The $\gcd(6,0) = \gcd(1\cdot6, 0\cdot 6) = 6$.

***

```{julia}
#The is an in-built gcd() function for integers (and a few more types) 
#but we'll soon make our own
using Random; Random.seed!(10)

a_test = *(rand(1:100,5)...)  
b_test = *(rand(1:100,5)...)
@show a_test, b_test
Base.gcd(a_test, b_test)
```

#### Euclid's Algorithm

The **Euclidean Algorithm** computes the gcd of two integers.  (Actually the Euclidean Algorithm computers gcds for any two elements of a *Euclidean Domain*).  The algorithm exploits the following property of the gcd:

##### Lemma {-}
Let $a,b\in \mathbb{Z}^{>0}$  and $a = b\cdot q + r$ with $r \in [0,b)$.  Then
1.  $\gcd(b, a) = \gcd(a, b)$,
1.  $\gcd(a, b) = gcd(r, b)$,
1.  $\gcd(a, b) = \gcd(a-b, b)$.

It is straightforward to turn this lemma into an algorithm:

```{julia}
function euclid_alg(a,b)
    (b == 0) && return a
    return euclid_alg(b, a % b)  # Rule 1 and 2
end

euclid_alg(2, 2*2), euclid_alg(3*7, 2*3), euclid_alg(2*2, 13)
```

```{julia}
Base.gcd(a_test, b_test), euclid_alg(a_test,b_test)
```

--- 

##### Extended Euclid's Algorithm

The **Extended Euclidean Algorithm** in addition to the **gcd(a, b)**, also computes $s$ and $t$ (called the Bézout coefficients) such that
$$as + bt = gcd(a,b).$$

```{julia}
function i_ext_euclid_alg(a,b)
    (a == 0) && return b, 0, 1
    g, s, t = i_ext_euclid_alg(b % a, a)
    return g, t - (b ÷ a)*s, s
end

pretty_print_egcd((a,b),(g,s,t)) = println("$a×$s + $b×$t = $g = gcd($a, $b)") #\times + [TAB]

for (a,b) in [(4,12), (9,12), (4,13)]
    pretty_print_egcd((a,b), i_ext_euclid_alg(a,b))
end
```

```{julia}
#Note there is an in-built gcdx - let's compare against that too
Base.gcdx(a_test,b_test), i_ext_euclid_alg(a_test,b_test)
```

```{julia}
?gcdx
```

--- 

### Inversion in $\mathbb{Z}_m$

Notice the Extended Euclidean Algorithm computes inverses in $\mathbb{Z}_m$.  Given $a \in \mathbb{Z}_m^{\neq 0}$ the ${\rm egcd}(a,m)$ returns $s$ and $t$ such that
$$
a \cdot s + m \cdot t = gcd(a,m).
$$
Taking the entire equation $\mod m$ we get
$$
\begin{align*}
&\gcd(a,m) \cong a \cdot s + m \cdot t ~\mod m  \\
&\implies \gcd(a,m) \cong a \cdot s + 0 ~\mod m  \\
&\implies \gcd(a,m) \cong a \cdot s ~\mod m.
\end{align*}
$$
Provided $\gcd(a,m) = 1$ (i.e. "coprime" or "relatively prime") we get $a \cdot s \cong 1 \mod m$ and thus $a^{-1} \cong s \mod m$.

##### Example {-}
To find the inverse of $5 \in \mathbb{Z}_{13}$ do:
```{julia}
a, m = 5, 13
i_ext_euclid_alg(5, 13)
```
```{julia}
inverse_mod(a,m) = mod(i_ext_euclid_alg(a,m)[2], m)
```
```{julia}
i = inverse_mod(a,m)
```
```{julia}
mod(a*i, m)
```
<!-- 
***

### Chinese Remaindering

##### Problem Statement
Two integers $a$ and $b$ are *relatively prime* when $\gcd(a,b) = 1$.  Given a finite sequence of relatively prime integers $m_1,\ldots,m_k$ called the *moduli* and correspoing integers $u_1,\ldots,u_k$ called the *images*, find $u \in \mathbb{Z}$ such that
\begin{align*}
u &\cong u_1 \mod m_1 \\
u &\cong u_2 \mod m_2 \\
&\; \vdots \\
u &\cong u_k \mod m_k
\end{align*}

#### Example
For example, given the following information
\begin{align*}
u &\cong 4 \mod 5 &\implies&& (u_1,\, m_1) &= (4,\, 5)\\
u &\cong 5 \mod 7 &\implies&& (u_2,\, m_2) &= (5,\, 7)
\end{align*}
we want to deduce $u = 19$ because

```{julia}
(19 % 5, 19 % 7)
```

***

##### Theorem (CRT)

Let $M = m_1 \cdot m_2 \cdots \cdot m_k$.  There exists a unique $u \in \mathbb{Z}$ on $\{0,\ldots,M-1\}$ such that $u \cong u_i \mod m_i$ for $i = 1,\ldots,k$.

**Proof of Existence**:

(This is a constructive proof which provides an algorithm for determining $u$).

Let 
$$
u = v_1 + v_2m_1 + v_3m_1m_2 + \cdots + v_{k+1} m_1 m_2 \cdots m_{k}
$$
and notice the vanishing terms after reducing $u$ modulo $m_j$:
$$
u \mod m_j = v_1 + v_2m_1 + \cdots + v_{j}m_1\cdots m_{j-1} + 0 + \cdots + 0
$$

We have
\begin{align*}
u_1 &\cong v_1 \mod m_1 &&\implies v_1 \gets u_1 \\
u_2 &\cong v_1 + v_2 m_1 \mod m_2 &&\implies v_2 \gets (u_2 - v_1) \cdot (m_1)^{-1} \mod m_2 \\
u_3 &\cong v_1 + v_2 m_1 + v_3 m_1 m_2 \mod m_3 &&\implies v_3 \gets (u_3-v_1-v_2 m_1)(m_1 m_2)^{-1} \mod m_3\\
&\;\,\vdots
\end{align*}

**Proof of Uniquenss**

Left as an exercise. :P

***

##### Example (CRT)

Suppose $u \cong 2 \mod 3$, $u \cong 1 \mod 5$, $u \cong 5 \mod 7$.  What is $u$?

Proceeding with CRT...

```{julia}
uᵢ = [2, 1, 5] # \_i + [TAB]
m = [3, 5, 7]
v = Vector{Int}(undef,3)

v[1] = uᵢ[1]
v[2] = (uᵢ[2] - v[1]) * inverse_mod(m[1], m[2]) % m[2]
v[3] = (uᵢ[3] - v[1] - v[2]*m[1]) * inverse_mod(m[1]*m[2], m[3]) % m[3]
@show v #intermediate 

u = v[1] + v[2]*m[1] + v[3]*m[1]*m[2]
for i in [1, 2, 3]
    # This line outputs Unicode character ≡ which causes LaTeX issues, so it's skipped
    # println("$u ≡ $(uᵢ[i]) mod $(m[i])")
    print("$u == $(uᵢ[i]) mod $(m[i])\n")
end
```

*** -->

## The Polynomial Ring $\mathcal{R}[x]$

By this point in your mathematics career you have surely worked with *polynomials*.  A polynomial is something like $x^2 + 2x + 1$ but *not* like $\frac{x^2+1}{x-1}$ or $x \sin(x)$.

### Definition 
Let $\mathcal{R}$ be a ring and $a \in \mathcal{R}[x]$.  Let 
$$
a = a_n x^n + a_{n-1}x^{n-1} + \cdots + a_1x + a_0
$$
with $a_n \neq 0$.

+ $a$ is called a **polynomial** in $x$ and $a_k x^k$ are its **terms**.
+ The **degree** of $a$ is $n$:  $\quad \deg(a) = n.$
* The **leading coefficient** of $a$ is $a_n$: $\quad{\rm lc}(a) = a_n.$
+ The **leading term** of $a$ is $a_n x^n$:  $\quad{\rm lt}(a) = a_n x^n.$

By convention we let ${\rm lc}(0) = {\rm lt}(0) = 0$ and $\deg(0) = - \infty$.

### Representation of Polynomials in this project

```{{julia}}
"""
A term.
"""
struct Term  #structs are immutable by default
    coeff::Int
    degree::Int
    function Term(coeff::Int, degree::Int)
        degree < 0 && error("Degree must be non-negative")
        coeff != 0 ? new(coeff,degree) : new(coeff,0)
    end
end

"""
Creates the zero term.
"""
zero(::Type{Term})::Term = Term(0,0)

"""
Creates the unit term.
"""
one(::Type{Term})::Term = Term(1,0)
```

```{julia}
x+x
```

```{{julia}}
"""
A Polynomial type - designed to be for polynomials with integer coefficients.
"""
struct Polynomial

    #A zero packed vector of terms
    #Terms are assumed to be in order
    #until the degree of the polynomial. The leading term (i.e. last) is assumed to be non-zero except 
    #for the zero polynomial where the vector is of length 1.
    #Note: at positions where the coefficient is 0, the power of the term is also 0 (this is how the Term type is designed)
    #The maximum length allowed for the vector is max_degree+1
    terms::Vector{Term}   
    
    #Inner constructor of 0 polynomial
    Polynomial() = new([zero(Term)])

    #Inner constructor of polynomial based on arbitrary list of terms
    function Polynomial(vt::Vector{Term})

        #Filter the vector so that there is not more than a single zero term
        vt = filter((t)->!iszero(t), vt)
        if isempty(vt)
            vt = [zero(Term)]
        end

        max_degree = maximum((t)->t.degree, vt)
        max_degree > max_degree_allowed && error("Cannot create polynomial of degree greater than $max_degree_allowed. You are trying $max_degree.")
        terms = [zero(Term) for i in 0:max_degree] #First set all terms with zeros

        #now update based on the input terms
        for t in vt
            terms[t.degree + 1] = t #+1 accounts for 1-indexing
        end
        return new(terms)
    end
end

"""
Construct a polynomial of the form x.
"""
x_poly() = Polynomial(Term(1,1))

"""
Creates the zero polynomial.
"""
zero(::Type{Polynomial})::Polynomial = Polynomial()

"""
Creates the unit polynomial.
"""
one(::Type{Polynomial})::Polynomial = Polynomial(one(Term))
one(p::Polynomial) = one(typeof(p))
```

### Addition in $\mathcal{R}[x]$

For $\mathcal{R}[x]$ to be a *ring* we must define addition.

```raw
def ADDITION: 
    Input   a, b in ZZ[x]
    Ouput   a + b (definitionally)
    
    if deg(a) == deg(b)
        term = lt(a) + lt(b)      # addtion on *terms* ax^n + bx^n = (a+b)x^n
        return term + ADDITION(a-lt(a), b-lt(b))
        
    if deg(a) > deg(b)
        return lt(a) + ADDITION(a-lt(a), b)
    
    # deg(b) > deg(a)
    return lt(b) + ADDITION(a, b-lt(b))
```

```{{julia}}
"""
Add a polynomial and an integer.
"""
+(p::Polynomial, n::Int) = p + Term(n,0)
+(n::Int, p::Polynomial) = p + Term(n,0)

"""
Add a polynomial and a term.
"""
function +(p::Polynomial, t::Term)
    p = deepcopy(p)
    if t.degree > degree(p)
        push!(p, t)
    else
        if !iszero(p.terms[t.degree + 1]) #+1 is due to indexing
            p.terms[t.degree + 1] += t
        else
            p.terms[t.degree + 1] = t
        end
    end

    return trim!(p)
end
+(t::Term, p::Polynomial) = p + t

"""
Add two polynomials.  Does not assume dense (or spart) representation
"""
function +(p1::Polynomial, p2::Polynomial)::Polynomial
    p = deepcopy(p1)
    for t in p2
        p += t
    end
    return p
end
```

```{julia}
x = x_poly(PolynomialDense)
p1 = 2x^2 + 3x + (-5) #Project: Fix this so we can simply do 2x^2+3x-5
p2 = -3x^2 - 4x + 6
p1+p2
```

### Multiplication in $\mathcal{R}[x]$

For $\mathcal{R}[x]$ to be a *ring* we must define multiplication.

```raw
def MULTIPLICATION: 
    Input   a, b in ZZ[x]
    Ouput   a * b (definitionally)
    
    if a = 0 or b = 0:
        return 0
    
    if lt(a) = a and lt(b) = b:   # a and b are single terms
        return a * b              # product of *terms* ax^n * bx^m = (ab)x^(n+m)
        
    write a = a1 + a2 with deg(a1) != deg(a2)
    write b = b1 + b2 with deg(b1) != deg(b2)
    
    # DISTRIBUTION PROPERTY
    # (a1 + a2)*(b1 + b2) = a1*b1 + a1*b2 + a2*b1 + a2*b2
    return M(a1,b1) + M(a1,b2) + M(a2,b1) + M(a2,b2) where M = MULTIPLICATION
```

```{{julia}}
"""
Multiplication of polynomial and term.
"""
*(t::Term, p1::Polynomial)::Polynomial = iszero(t) ? Polynomial() : Polynomial(map((pt)->t*pt, p1.terms))
*(p1::Polynomial, t::Term)::Polynomial = t*p1

"""
Multiplication of polynomial and polynomial.
"""
function *(p1::Polynomial, p2::Polynomial)::Polynomial
    p_out = Polynomial()
    for t in p1
        p_out = p_out + (t * p2)
    end
    return p_out
end
```

```{julia}
x = x_poly(PolynomialDense)
p1 = 2x^2 + 3x + (-5)
p2 = -3x^2 - 4x + 6
p1 * p2
```

The following properties are consequences of our definition.  (They are obligated to be).

##### Proposition (Polynomial Multiplication)
When $\mathcal{R}$ is an **integral domain** (a nonzero commutative ring in which the product of any two nonzero elements is nonzero) and $a,b \in \mathcal{R}[x]^{\neq 0}$ then
1.  $\deg(ab) = \deg a + \deg b$,
1.  ${\rm lc}(ab) = a_b \cdot b_m = {\rm lc}(a) \cdot {\rm lc}(b)$,
1.  ${\rm lm}(ab) = {\rm lm}(a) \cdot {\rm lm}(b)$,
1.  ${\rm lt}(ab) = {\rm lt}(a) \cdot {\rm lt}(b)$.

*Proof* (Sketch)
$$
\begin{align*}
a \times b &= (a_n x^n + \cdots + a_0)(b_mx^m + \cdots + b_0) \\
&= a_n \cdot b_m x^{n+m} + \cdots + a_0 \cdot b_0
\end{align*}
$$

##### Proposition
Every field is also an integral domain.

*Proof* (Omitted)
<!-- 
### Multiplication by Chinese Remainder Theorem (Project)

Let $a = a_nx^n + a_{n-1}x^{n-1} + \cdots + a_1 x + a_0$.  Define the **height** of a polynomial by
$$
||a||_{\infty} := \max\{|a_0|, \ldots, |a_n|\}.
$$
So, for instance $||2x^2-5||_{\infty} = 5$.

Further let 
$$\# a := \mbox{number of nonzero terms of }a.$$  
So, for instance $\# 2x^2-5 = 2$.

If we intend to use CRT to cacluate the product $c = a \cdot b$ of $a,b \in \mathbb{Z}_p[x]$ we need $M = p_1,\ldots,p_\ell$ satisfying
$$
M = p_1 \cdot \cdots \cdot p_\ell > 2 \cdot ||c||_\infty.
$$
It is *twice* $||c||_\infty$ to account for negative ceofficients.  For instance, $3x^2 - 3x +1$ requires coefficients in $\{ -3,-2,-1,0,1,2,3\}$ which is $\mathbb{Z}_7$ and not $\mathbb{Z}_5$.

##### Proposition
Let $a,b \in \mathbb{Z}[x]$.
$$
||c||_{\infty} \leq ||a||_{\infty} \cdot ||b||_{\infty} \cdot \min(\# a,\, \# b)
$$

*Proof* (Sketch)
Do a worst case analysis where you mutiply $a = \alpha x^n + \alpha x^{n-1} + \cdots + \alpha$ by  $b = \beta x^n + \beta x^{n-1} + \cdots + \beta$ and see what the largest coefficient will end up being.

##### Example 
Let
\begin{align*}
a = 3x - 4, && b = 6x+5, && c = 18x^2-9x-20
\end{align*}
and notice $ab = c$.

$$||c||_\infty \leq 4 \cdot 6 \cdot \min(2,2) = 48$$

$$
\begin{align*}
& && a_i && b_i && c_i \\[1em]
\hline
p_1 &= 5 && 3x + 1 && 1x + 0 && 3x^2 + 1x + 0 \\[1.5em]
\hline
p_2 &= 7 && 3x + 3 && 6x + 5 && 4x^2 + 5x + 1 \\[1.5em]
\hline
p_3 &= 3 && 0x + 2 && 0x + 2 && 0x^2 + 0x + 1 \\[1.5em]
\hline
\end{align*}
$$

Suppose you have defined a function:

    CRT([u1, u2, ..., um], [p1, p2, ..., pm]) = u  such that u == uk mod pk

```{julia}
CRT([3,4,0], [5,7,3]) = 18 mod 3*5*7
CRT([1,5,0], [5,7,3]) = 96 mod 3*5*7
CRT([0,1,1], [5,7,3]) = 85 mod 3*5*7
```

Let the **symmetric mod** be given by

    smod(a, m) = (a mod m) if (a mod m) <= m//2 else (a mod m) - m

For instance, 

    smod(0, 7) = 0
    smod(1, 7) = 1
    smod(2, 7) = 2
    smod(3, 7) = 3
    smod(4, 7) = -3
    smod(5, 7) = -2
    smod(6, 7) = -1

```{julia}
CRT([3,4,0], [5,7,3]) = 18 mod 3*5*7
CRT([1,5,0], [5,7,3]) = 96 mod 3*5*7 = -9 smod 3*5*7 
CRT([0,1,1], [5,7,3]) = 85 mod 3*5*7 = -20 smod 3*5*7 
```

$$
\begin{align*}
& && a_i && b_i && c_i \\[1em]
\hline
p_1 &= 5 && 3x + 1 && 1x + 0 && 3x^2 + 1x + 0 \\[1.5em]
\hline
p_2 &= 7 && 3x + 3 && 6x + 5 && 4x^2 + 5x + 1 \\[1.5em]
\hline
p_3 &= 3 && 0x + 2 && 0x + 2 && 0x^2 + 0x + 1 \\[1.5em]
\hline
p &= 105 && 3x + 101 && 6x+5 && 18x^2 + 96 x + 85 \\[1.5em]
\hline
\end{align*}
$$

So we, apply the symmetric mod and deduce $$(3x - 4)(6x+5) = 18x^2 -9x - 20.$$

```raw
Chinese Remainder Theorem on TWO polynomials

def CRT:
    Input   [a,b] and [n,m] 
                such that a in \mathbb{Z}_n[x], b in \mathbb{Z}_m[x], and gcd(n,m)=1.
    Ouput   c \in \mathbb{Z}_{nm}[x] 
                such that c ≡ a (mod n) and c ≡ b (mod m).
    
    c <- 0                             # the 0 polynomial
    for k from max(deg a, deg b) to 0 by -1 do
        ak <- 0 if k > deg a else ak   # = coefficient on x^k in a
        bk <- 0 if k > deg b else bk   # = coefficient on x^k in b
        ck <- iCRT([ak, bk], [n, m])   # integer chinese remainder
        c  <- c + ck * x^k
    
    return c
```

```raw
def MULTIPLICATION: 
    Input   a = an x^n + ... a1 x + a0, b = bm x^m + ... b1 x + b0 in ZZ[x]
    Ouput   a * b in ZZ[x]
    
    height_a <- max(|an|, ..., |a1|, |a0|)
    height_b <- max(|bm|, ..., |b1|, |b0|)
    
    B <- 2 * height_a * height_b * min(n+1, m+1)
    p <- 3
    M <- p
    c <- (a*b) mod M          # multiplication in ZZ_3[x]
    
    while M < B do
       p  <- NextPrime(p)     # the first prime > p
       c' <- a*b mod p        # multiplication in ZZ_p[x]
       c  <- CRT([c, c'], [M, p])  # spatial optimaztion 
       M  <- M*p
         
    return c smod M           # restore negative coefficients with symemetric mod
``` -->

### Division in $\mathbb{F}[x]$

We are unable to *divide* in $\mathcal{R}[x]$.  Consider the following operation in $\mathbb{Z}[x]$
$$
\frac{x^2}{2x} = \frac{1}{2}x.
$$
Even though $x^2$ and $2x$ are from $\mathbb{Z}[x]$ that their division is in $\mathbb{Q}[x]$.  This is because $\mathbb{Z}$ is not a *field* but $\mathbb{Q}$ is.  

It turns out $\mathbb{F}[x]$ is a **Euclidean Domain** when $\mathbb{F}$ is a field.  Re-consider the division, but this time let us do the calcuation in $\mathbb{Z}_7[x]$
$$
\begin{align*}
\frac{x^2}{2x} 
&\cong \frac{1}{2}x \mod 7 \\
&\cong 2^{-1} x \mod 7 \\
&\cong 4 x \mod 7.
\end{align*}
$$
Note that $\frac{1}{2} \cong 4 \mod 7$.

#### Theorem (Division in $\mathbb{F}[x]$) 
Let $a,b \in \mathbb{F}[x]$, $b\neq0$.  There exists *unique* polynomials $q,r \in \mathbb{F}[x]$ such that 
$$
\begin{align*}
a = bq + r &&\mbox{and}&& r = 0 &&\mbox{or}&& \deg r < \deg b
\end{align*}
$$

*Proof* (Uniqueness) 
Let $a = b q_1 + r_1 = b q_2 + r_2$ with $\deg r_1, \deg r_2 < \deg b$.

Consider
$$
\begin{align*}
b q_1 + r_1 = b q_2 + r_2 
&\implies b(q_1 - q_2) = (r_2-r_1) \\
&\implies b | (r_2-r_1) & \mbox{But }\deg r_1, r_2 < \deg b\\
&\implies r_2 - r_1 = 0 \\
&\implies r_2 = r_1
\end{align*}
$$

Therefore $b(q_1-q_2) = 0$. But since $\mathbb{F}[x]$ is an integral domain it cannot have zero divisors. As we assumed $b\neq 0$ this implies $$(q_1-q_2)=0 \implies q_1 = q_2. ~\square$$

*Proof* (Existence -- The Division Algorithm)

```raw
def DIVISION: 
    Input   a, b in ZZ_p[x] such that b != 0
    Ouput   q, r such that a = b*q + r and deg r < deg b in ZZ_p[x]
    
    r, q = a, 0
    while r != 0 and deg r >= deg b do:
        t <- lt(r)/lt(b)    # division of *terms* in ZZ_p: (ax^n)/(bx^m) = a/b mod p x^(n-m), n>m
        q <- q + t
        r <- r - t*b        # deg r *must* monotonically decrease
    return (q,r)
    
A couple of convenience methods

def QUO(a, b) = first(DIVISION(a,b)) in ZZ_p[x]
def REM(a, b) = first(DIVISION(a,b)) in ZZ_p[x]
```

```{julia}
function div(t1::Term{C, D}, t2::Term{C, D}) where {C, D} # Base.:÷
    @assert t1.degree >= t2.degree
    return p->Term(mod(t1.coeff*int_inverse_mod(t2.coeff,p),p), t1.degree - t2.degree)
end


#At the moment, the divide function and it's friends (÷ and rem) return a function that then uses a prime to return an actual polynomial
function divide(num::Polynomial, den::Polynomial)
    function division_function(p::Int)
        f, g = mod(num,p), mod(den,p)
        degree(f) < degree(num) && return nothing 
        iszero(g) && throw(DivideError())
        q = typeof(num)()
        prev_degree = degree(f)
        while degree(f) >= degree(g) 
            h = typeof(num)( (leading(f) ÷ leading(g))(p) )  #syzergy 
            f = mod((f - h*g), p)
            q = mod((q + h), p)  
            prev_degree == degree(f) && break
            prev_degree = degree(f)
        end
        @assert iszero( mod((num  - (q*g + f)),p))
        return q, f
    end
    return division_function
end

"""
The quotient from polynomial division. Returns a function of an integer.
"""
÷(num::Polynomial, den::Polynomial)  = (p::Int) -> first(divide(num,den)(p))

"""
The remainder from polynomial division. Returns a function of an integer.
"""
rem(num::Polynomial, den::Polynomial)  = (p::Int) -> last(divide(num,den)(p))
```

```{julia}
@show p1
@show p2
divide(p1, p2)
```

```{julia}
q , r = divide(p1,p2)(101)
```

```{julia}
q = (p1 ÷ p2)(101) #Not the nicest interface, but will be nicer with PolynomialModP
```

```{julia}
r = rem(p1,p2)(101) #Not the nicest interface, but will be nicer with PolynomialModP
```

```{julia}
mod(q*p2+r - p1,101)
```

##### Example {-}
Consider $a = 10x^2 + 4x + 1$ divided by $b = 5x-3$ in $\mathbb{Z}_{11}[x]$.

$$
\begin{align*}
r,q &\gets 10x^2 + 4x + 1, 0 \\[1em]
r \neq 0 &\mbox{ and } \deg r = 2 \geq \deg b = 1 \\
t &\gets \frac{10x^2}{5x} \cong 2x \mod 11\\
q &\gets 0 + 2x\\
r &\gets (10x^2 + 4x + 1) - 2x(5x-3) \cong 10x + 1 \mod 11\\[1em]
r \neq 0 &\mbox{ and } \deg r = 1 \geq \deg b = 1 \\
t &\gets \frac{10x}{5x} \cong 2 \mod 11\\
q &\gets 2x + 2\\
r &\gets (10x+1) - 2(5x-3) \cong 7 \mod 11\\[1em]
r \neq 0 &\mbox{ and } \color{red}{\deg r = 0 \geq \deg b = 1} \\[1em]
&\mbox{return } (2x+2, 7)
\end{align*}
$$

And notice $10x^2 + 4x + 1 \cong (5x-3)(2x+2) + 7 \mod 11$.

### GCDs in $\mathbb{Z}_p[x]$

#### Theorem 
Let $a,b \in \mathbb{Z}_p[x]^{\neq 0}$. There is $s,t \in \mathbb{Z}_p[x]$ such that
$$
sa + tb = \gcd(a,b).
$$

*Proof:* The extended Euclidean Algorithm

```{julia}
#Taken from polynomial_gcd.jl
#Note that as part of your project you'll implelment this for PolynomialModP 
#(without an input argument `prime`)

function extended_euclid_alg(a::Polynomial, b::Polynomial, prime::Int)
    old_r, r = mod(a,prime), mod(b,prime)
    old_s, s = one(typeof(a)), zero(typeof(a))
    old_t, t = zero(typeof(a)), one(typeof(a))

    while !iszero(mod(r,prime))
        q = divide(old_r, r)(prime) |> first    # |> is the pipe operator
        old_r, r = r, mod(old_r - q*r, prime)
        old_s, s = s, mod(old_s - q*s, prime)
        old_t, t = t, mod(old_t - q*t, prime)
    end
    g, s, t = old_r, old_s, old_t
    @assert mod(s*a + t*b - g, prime) == 0
    return g, s, t  
end
```

```{julia}
x = x_poly(PolynomialDense)
p1 = 2x^2+3x +(-5) #Note we need +(-5)... try later without... how to fix?
p2 = -3x^2 - 4x +6

extended_euclid_alg(p1*p2, p2, 101)
```

